name: semcomp2019
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - jupyter=1.0.0
  - notebook=6.0.1
  - black=19.3b0
  - seaborn=0.9.0
  - numpy=1.17.2
  - pandas=0.25.1
  - scikit-learn=0.21.3
  - tqdm==4.36.1
  - pip:
      - jaxlib==0.1.29
      - jax==0.1.46
      - graphviz==0.13
